#!/bin/bash
export BASEDIR=/xLights
mkdir ${BASEDIR}
cd ${BASEDIR}
git clone https://github.com/xLightsSequencer/xLights.git --recurse-submodules xlights-git
cd ${BASEDIR}/xlights-git
git pull
colormake-short -j`nproc`
